# Generated by Django 4.2.11 on 2024-04-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'st_categorias',
            },
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('beneficiario', models.CharField(max_length=150)),
                ('monto_recaudar', models.DecimalField(decimal_places=2, max_digits=9)),
                ('monto_recaudado', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='campanias', to='campania.categoria')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'st_campania',
            },
        ),
    ]
